# 日志配置

version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

loggers:
  tca:
    level: INFO
    handlers:
      - console
    propagate: no

root:
  level: WARNING
  handlers:
    - console
